--INSERT INTO roles(id, name) VALUES(111, 'ROLE_USER');
--INSERT INTO roles(id, name) VALUES(222, 'ROLE_MODERATOR');
--INSERT INTO roles(id, name) VALUES(333, 'ROLE_ADMIN');

INSERT INTO roles(id, name) VALUES(1, 'ROLE_MODERATOR');
--INSERT INTO user_roles VALUES(11,10);
--INSERT INTO user_roles VALUES(11,1);
--INSERT INTO user_roles VALUES(11,1);